#!bin/sh

# cleanup
rm -rf obj_dir
rm -f simplecpu.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace simplecpu.sv --exe simple_riscv_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsimplecpu.mk Vsimplecpu

# run executable simulation file
obj_dir/Vsimplecpu